"""
Document generation utilities for Assignment AI.
Handles creation of Word, PowerPoint, and PDF files.
"""
import io
import re
from django.conf import settings


def generate_word_document(content, title):
    """Generate a Word document from content."""
    try:
        from docx import Document
        from docx.shared import Inches, Pt
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        
        doc = Document()
        
        doc.add_heading(title, 0)
        
        paragraphs = content.split('\n\n')
        for para in paragraphs:
            para = para.strip()
            if not para:
                continue
            
            if para.startswith('# '):
                doc.add_heading(para[2:], 0)
            elif para.startswith('## '):
                doc.add_heading(para[3:], 1)
            elif para.startswith('### '):
                doc.add_heading(para[4:], 2)
            elif para.startswith('- ') or para.startswith('* '):
                for item in para.split('\n'):
                    if item.strip():
                        doc.add_paragraph(item.strip(), style='List Bullet')
            else:
                p = doc.add_paragraph(para)
                p_format = p.paragraph_format
                p_format.line_spacing = 1.5
        
        doc.save(io.BytesIO())
        return doc
    except Exception as e:
        raise Exception(f"Error generating Word document: {str(e)}")


def generate_powerpoint_slides(content, title):
    """Generate a PowerPoint presentation from content."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.enum.text import PP_ALIGN
        
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)
        
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = title
        subtitle.text = "Generated by NEXA AI Assignment Assistant"
        
        content_lines = content.split('\n')
        current_slide = None
        current_text = []
        slide_count = 0
        
        for line in content_lines:
            line = line.strip()
            if not line:
                continue
            
            if line.startswith('# ') or line.startswith('## '):
                if current_text:
                    _add_content_slide(prs, current_title, current_text)
                    slide_count += 1
                    current_text = []
                
                current_title = line.lstrip('# ').strip()
                
                if slide_count >= 10:
                    break
            elif line.startswith('- ') or line.startswith('* '):
                current_text.append(line.lstrip('- *').strip())
            elif len(current_text) > 0:
                current_text.append(line)
        
        if current_text:
            _add_content_slide(prs, current_title or "Content", current_text)
        
        prs.save(io.BytesIO())
        return prs
    except Exception as e:
        raise Exception(f"Error generating PowerPoint: {str(e)}")


def _add_content_slide(prs, title_text, content_lines):
    """Add a content slide to the presentation."""
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    
    title_shape.text = title_text
    
    tf = body_shape.text_frame
    tf.clear()
    
    for item in content_lines[:8]:
        p = tf.add_paragraph()
        p.text = item
        p.level = 0


def generate_pdf_document(content, title):
    """Generate a PDF document from content."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER
        )
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            spaceBefore=20
        )
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            alignment=TA_LEFT
        )
        
        story = []
        
        story.append(Paragraph(title, title_style))
        
        paragraphs = content.split('\n\n')
        for para in paragraphs:
            para = para.strip()
            if not para:
                continue
            
            if para.startswith('# '):
                story.append(Paragraph(para[2:], heading_style))
            elif para.startswith('## '):
                story.append(Paragraph(para[3:], heading_style))
            elif para.startswith('### '):
                story.append(Paragraph(para[4:], heading_style))
            else:
                para_clean = para.replace('\n', '<br/>')
                story.append(Paragraph(para_clean, body_style))
                story.append(Spacer(1, 6))
        
        doc.build(story)
        return buffer
    except Exception as e:
        raise Exception(f"Error generating PDF: {str(e)}")


def extract_text_from_file(file):
    """Extract text from uploaded file based on file type."""
    import PyPDF2
    
    text = ""
    file_name = file.name.lower()
    
    try:
        if file_name.endswith('.pdf'):
            pdf_reader = PyPDF2.PdfReader(file)
            for page in pdf_reader.pages:
                text += page.extract_text() or ""
        
        elif file_name.endswith('.docx'):
            from docx import Document
            doc = Document(file)
            for para in doc.paragraphs:
                text += para.text + "\n"
        
        elif file_name.endswith('.pptx') or file_name.endswith('.ppt'):
            from pptx import Presentation
            prs = Presentation(file)
            for slide in prs.slides:
                for shape in slide.shapes:
                    if hasattr(shape, "text"):
                        text += shape.text + "\n"
        
        elif file_name.endswith('.txt'):
            text = file.read().decode('utf-8', errors='ignore')
        
        return text
    except Exception as e:
        return f"[Could not extract text from file: {str(e)}]"
