# Generated by Django 4.2.29 on 2026-03-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
