# Generated by Django 4.2.29 on 2026-04-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tutorial_complete',
            field=models.BooleanField(default=False),
        ),
    ]
