# Generated by Django 6.0.3 on 2026-03-06 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='study_materials/')),
                ('material_type', models.CharField(choices=[('PDF', 'PDF'), ('PowerPoint', 'PowerPoint'), ('Word', 'Word'), ('Slides', 'Slides')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Extracted text from the file for AI/RAG integration')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
