# Generated by Django 4.2.29 on 2026-03-21 23:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/study_materials/', location='C:\\Users\\danie\\Downloads\\UNIXA-main\\media\\study_materials'), upload_to=''),
        ),
    ]
