# Generated by Django 4.2.29 on 2026-03-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0004_savedpodcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStudySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('lyrics_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_songs', to='materials.studymaterial')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
