# Generated by Django 4.2.29 on 2026-03-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_savedstudysong'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='extracted_pages_json',
            field=models.JSONField(blank=True, help_text='Cache for extracted slides (text + images)', null=True),
        ),
    ]
