# Generated by Django 4.2.29 on 2026-04-04 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0006_studymaterial_extracted_pages_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='materials.studymaterial')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_concepts', to='materials.conceptnode')),
            ],
        ),
        migrations.CreateModel(
            name='StudentConceptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_strength', models.IntegerField(default=0, help_text='Calculated mastery from 0 to 100')),
                ('confidence_calibration', models.IntegerField(default=0, help_text='Difference between self-reported confidence and actual performance')),
                ('error_profile', models.JSONField(blank=True, default=dict, help_text='Tracks error types (misconception, careless, etc.)')),
                ('response_velocity', models.FloatField(default=0.0, help_text='Average time taken to answer in seconds')),
                ('forgetting_risk_score', models.FloatField(default=0.0, help_text='Live score representing risk of forgetting')),
                ('last_reviewed', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_states', to='materials.conceptnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'concept')},
            },
        ),
    ]
