# Generated by Django 4.2.29 on 2026-03-19 18:24

import community.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_post_feed_only_title_commentlike_communityprofile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='block',
            name='unique_block',
        ),
        migrations.RemoveConstraint(
            model_name='communitymembership',
            name='unique_user_community',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.RemoveConstraint(
            model_name='postlike',
            name='unique_user_post_like',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='community_m_convers_5abe6c_idx',
            old_name='msg_conv_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='community_m_sender__13e3b6_idx',
            old_name='msg_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_created_d02d22_idx',
            old_name='post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_school__53a377_idx',
            old_name='post_school_comm_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_custom__3c53e8_idx',
            old_name='post_custom_comm_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_author__54f6fb_idx',
            old_name='post_author_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_is_dele_98519f_idx',
            old_name='post_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='postlike',
            new_name='community_p_post_id_e3bcaf_idx',
            old_name='postlike_post_idx',
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customcommunity',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('comment_like', 'Comment Like'), ('follow', 'Follow'), ('mention', 'Mention'), ('join', 'Join')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolcommunity',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='space',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
