# Generated by Django 4.2.29 on 2026-03-20 08:56

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_group_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcommunity',
            name='is_mature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customcommunity',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customcommunity',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupworkspace',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('voice', 'Voice Note'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='workspacefile',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspacemessage',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
