# Generated by Django 4.2.29 on 2026-03-20 09:41

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0008_seed_ghana_universities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('comment_like', 'Comment Like'), ('follow', 'Follow'), ('mention', 'Mention'), ('join', 'Join'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted')], max_length=20),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='CustomCommunityMembership',
            fields=[
                ('id', models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.customcommunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Community Membership',
                'verbose_name_plural': 'Custom Community Memberships',
                'unique_together': {('user', 'community')},
            },
        ),
    ]
