# Generated by Django 4.2.29 on 2026-03-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_add_friendship_custom_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
