# Generated by Django 4.2.29 on 2026-03-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_add_profile_display_name_location_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('comment_like', 'Comment Like'), ('follow', 'Follow'), ('mention', 'Mention'), ('join', 'Join'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('message', 'Message')], max_length=20),
        ),
    ]
