# Generated by Django 4.2.29 on 2026-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_add_conversation_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcommunity',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
