# Generated by Django 4.2.29 on 2026-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_fix_university_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkspace',
            name='workspace_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('study_group', 'Study Group'), ('group_project', 'Group Project'), ('general', 'General Collaboration')], default='general', max_length=20),
        ),
    ]
