# Generated by Django 4.2.29 on 2026-03-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_add_workspace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacetask',
            name='review_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='review_status',
            field=models.CharField(choices=[('none', 'No submission'), ('pending', 'Pending review'), ('approved', 'Approved'), ('revision', 'Revision requested')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='submission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
