# Generated by Django 4.2.29 on 2026-03-21 16:18

import community.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_backfill_is_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='community.workspacemessage'),
        ),
        migrations.AlterField(
            model_name='groupworkspace',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private (invite only)'), ('request', 'Visible, join by request'), ('public', 'Public (anyone can join)')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
