# Generated by Django 4.2.29 on 2026-03-22 15:24

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_live_campus_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pulseevent',
            new_name='community_p_expires_6dd6fb_idx',
            old_name='community_p_expires_idx',
        ),
        migrations.AddField(
            model_name='pulseevent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pulse/'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='confessionreply',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='confessionupvote',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='helpbeacon',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microroom',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microroomparticipant',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nexaworkspacelink',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pulseevent',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pulsejoin',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skilldeal',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skilloffer',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startupfollow',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startupmember',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startupupdate',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
