# Generated by Django 4.2.29 on 2026-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_add_pulse_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('comment_like', 'Comment Like'), ('follow', 'Follow'), ('mention', 'Mention'), ('join', 'Join'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('message', 'Message'), ('live', 'Live')], max_length=20),
        ),
    ]
