# Generated by Django 4.2.29 on 2026-03-23 23:28

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_add_peer_to_workspace_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomsignal',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='is_opportunity',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='opportunity_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('scholarship', 'Scholarship'), ('job', 'Job'), ('competition', 'Competition'), ('research', 'Research'), ('grant', 'Grant'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nexadraft',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nexadraft',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='nexadraft',
            name='tool',
            field=models.CharField(choices=[('chat', 'AI Chat'), ('search', 'Deep Search'), ('essay', 'AI Writer'), ('para', 'Paraphraser'), ('cite', 'Citation Generator'), ('extract', 'Extract Data'), ('lit', 'Literature Review'), ('topics', 'Find Topics'), ('pdf', 'Chat with PDF'), ('tutor', 'AI Tutor')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nexasynclog',
            name='action',
            field=models.CharField(choices=[('push', 'Push'), ('sync', 'Sync'), ('recall', 'Recall')], default='push', max_length=10),
        ),
        migrations.AlterField(
            model_name='nexasynclog',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomsignal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskactivitylog',
            name='id',
            field=models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='roomsignal',
            index=models.Index(fields=['room', 'target', 'consumed', 'created_at'], name='community_r_room_id_44c46d_idx'),
        ),
    ]
