# Generated by Django 4.2.29 on 2026-03-29 14:26

import community.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0034_story_storyview_storylike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkspace',
            name='is_project_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupworkspace',
            name='project_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='groupworkspace',
            name='project_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskWorksheet',
            fields=[
                ('id', models.UUIDField(default=community.models._uuid, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('ai_notes', models.TextField(blank=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet', to='community.workspacetask')),
            ],
        ),
    ]
