# Generated by Django 4.2.29 on 2026-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_groupworkspace_is_project_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefile',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacefile',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
