# Generated by Django 4.2.29 on 2026-04-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0036_workspacefile_ai_metadata_workspacefile_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='match_prefs',
            field=models.CharField(blank=True, help_text='Comma-separated matching preferences', max_length=500),
        ),
    ]
