# Generated by Django 4.2.29 on 2026-04-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0037_communityprofile_major_communityprofile_match_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_ai_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
