# Generated by Django 4.2.29 on 2026-04-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_post_is_ai_generated_post_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='opportunity_type',
            field=models.CharField(blank=True, choices=[('grant', 'Grant'), ('freelance', 'Freelance Gig'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
