# Generated by Django 4.2.29 on 2026-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0039_alter_post_opportunity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='opportunity_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('job', 'Job'), ('scholarship', 'Scholarship'), ('grant', 'Grant'), ('freelance', 'Freelance Gig'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
