# Generated by Django 6.0.3 on 2026-03-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="User's message to the AI")),
                ('response', models.TextField(help_text="AI's response")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EssayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Essay topic', max_length=500)),
                ('research_done', models.BooleanField(default=False, help_text='Whether research was performed')),
                ('essay_text', models.TextField(help_text='Generated essay text')),
                ('output_format', models.CharField(choices=[('text', 'Plain Text'), ('pdf', 'PDF Document'), ('word', 'Word Document'), ('powerpoint', 'PowerPoint Presentation')], default='text', help_text='Desired output format', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Essay Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
