# Generated by Django 6.0.3 on 2026-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayrequest',
            name='word_count',
            field=models.PositiveIntegerField(default=500, help_text='Target word count for the essay'),
        ),
    ]
