# Generated by Django 6.0.3 on 2026-03-06 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Uploaded assignment file (PDF, Word, PowerPoint)', null=True, upload_to='assignments/')),
                ('text_content', models.TextField(blank=True, default='', help_text='Manual assignment instructions/text')),
                ('task_type', models.CharField(choices=[('essay', 'Write an Essay'), ('summarize', 'Summarize'), ('answer', 'Answer Questions'), ('slides', 'Generate Slides'), ('structured', 'Provide Structured Answers')], default='essay', max_length=20)),
                ('instructions', models.TextField(blank=True, default='', help_text='Additional instructions for the AI')),
                ('output_format', models.CharField(choices=[('word', 'Microsoft Word (.docx)'), ('powerpoint', 'PowerPoint (.pptx)'), ('pdf', 'PDF Document (.pdf)'), ('text', 'Plain Text')], default='word', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Generated content from AI')),
                ('result_file', models.FileField(blank=True, help_text='Generated file in selected format', null=True, upload_to='assignment_results/')),
                ('used_materials', models.TextField(blank=True, default='', help_text='Study materials used for RAG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assignment.assignment')),
            ],
            options={
                'verbose_name': 'Assignment Result',
                'verbose_name_plural': 'Assignment Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
