# Generated by Django 4.2.29 on 2026-03-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('assignment', '0003_assignment_use_rag'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='selected_materials',
            field=models.ManyToManyField(blank=True, help_text='Specific study materials to use (empty = use all)', related_name='assignments', to='materials.studymaterial'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
