# Generated by Django 4.2.29 on 2026-04-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_alter_assignment_id_alter_assignmentresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='research_notes',
            field=models.TextField(blank=True, default='', help_text='Findings from deep web research'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='research_sources',
            field=models.JSONField(blank=True, default=dict, help_text='Sources found during research (JSON list)'),
        ),
    ]
