# Generated by Django 4.2.29 on 2026-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_assignment_research_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task_type',
            field=models.CharField(choices=[('essay', 'Essays & Written Reports'), ('research', 'Deep Research Projects'), ('coding', 'Practical / Coding Assignments'), ('lab_report', 'Scientific Lab Reports'), ('presentation', 'Presentations & Slides'), ('problem_set', 'Problem Sets & Calculations'), ('group', 'Group Projects & Startup Systems'), ('case_study', 'Real-world Case Studies'), ('capstone', 'Capstone / Final Year Project')], default='essay', max_length=20),
        ),
    ]
