# Generated by Django 4.2.29 on 2026-03-23 23:57

import ai_community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimatch',
            name='id',
            field=models.UUIDField(default=ai_community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiopportunity',
            name='id',
            field=models.UUIDField(default=ai_community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expertbadge',
            name='id',
            field=models.UUIDField(default=ai_community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='ai_intro',
            field=models.TextField(blank=True, help_text='AI-generated team introduction'),
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='id',
            field=models.UUIDField(default=ai_community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='required_roles',
            field=models.TextField(blank=True, help_text='Comma-separated roles needed'),
        ),
        migrations.AlterField(
            model_name='startupteammember',
            name='id',
            field=models.UUIDField(default=ai_community.models._uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiprofile',
            name='courses',
            field=models.TextField(blank=True, help_text='Comma-separated courses'),
        ),
        migrations.AlterField(
            model_name='useraiprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests'),
        ),
        migrations.AlterField(
            model_name='useraiprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
