# Generated by Django 4.2.29 on 2026-04-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_community', '0002_alter_aimatch_id_alter_aiopportunity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiopportunity',
            name='opp_type',
            field=models.CharField(choices=[('grant', 'Grant'), ('freelance', 'Freelance Gig'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
